config/routes.rb
Bloccit::Application.routes.draw do

  get "posts/index"
  get 'tags/:tag', to: 'posts#index', as: :tag
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }


    resources :users, only: [:update, :show, :index]
    resources :posts, only: [:index]
    resources  :topics do
      resources :posts, except: [:index], controller: 'topics/posts' do
        resources :comments, only: [:create, :destroy]
        get '/up-vote' => 'votes#up_vote', as: :up_vote
        get '/down-vote' => 'votes#down_vote', as: :down_vote
        resources :favorites, only: [:create, :destroy]
      end
    end

  get 'autocomplete_location' => 'topics/posts#autocomplete_location'
  get 'about' => 'welcome#about'
  get 'index' => 'welcome#index'
  get 'privacypolicy' => 'welcome#privacypolicy'
  root to: 'welcome#index'
  
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts, dependent: :destroy

  scope :public, -> { where(public: true) }
  scope :private, -> { where(public: false) }
  scope :visible_to, ->(user) {user ? all : where(public: true)}
end

app/controllers/topics/posts_controller.rb
class Topics::PostsController < ApplicationController
 
  def show
    @topic = Topic.find(params[:topic_id])
    authorize @topic
    @post = Post.find(params[:id])

    @comments = @post.comments
    @comment = Comment.new
  end


  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
    authorize @post
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = current_user.posts.build(post_params)
    @post.topic = @topic
    authorize @post

    if @post.save
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @post  = Post.find(params[:id])
    title = @post.title
    authorize @post

    if @post.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully."
      redirect_to @topic
    else
      flash[:error] = "There was an error deleting the post."
      redirect_to :show
    end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
    if @post.update_attributes(post_params)
      flash[:notice] = "Post was updated."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error updating the post. Please try again."
      render :edit
    end
  end

  def autocomplete_location
    location = Geocoder.search(params["term"])
    json = location.collect do |item| 
     { "id" => item.postal_code.to_s, 
       "label" => item.address, 
       "value" => item.address  
     }
   end
    render json: json
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image, :tag_list, :location_id, :geolocation)
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.visible_to(current_user).paginate(page: params[:page], per_page: 10)
    authorize @topics
  end

  def new
    @topic = Topic.new
    authorize @topic
  end

  def create
   @topic = Topic.new(topic_params)
    authorize @topic
    if @topic.save
      flash[:notice] = "Topic was saved."
      redirect_to @topic
    else
      flash[:error] = "There was an error saving your topic. Please try again."
      render :new
    end
  end

  def show
    @topic = Topic.find(params[:id]) 
    authorize @topic  
    @posts = @topic.posts.includes(:user).includes(:comments).paginate(page: params[:page], per_page: 10)
  end

  def edit
    @topic = Topic.find(params[:id])
    authorize @topic
  end

  def destroy
    @topic = Topic.find(params[:id])
    name = @topic.name
    
    authorize @topic

    if @topic.destroy
      flash[:notice] = "\"#{name}\" was deleted successfully."
      redirect_to topics_path
    else
      flash[:error] = "There was an erorr deleting the topic."
      render :show
    end

  end


  def update
    @topic = Topic.find(params[:id])
    authorize @topic
    if @topic.update_attributes(topic_params)
      redirect_to @topic
    else
      flash[:error] = "There was an error updating your topic. Please try again."
      render :edit
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:name,:description,:public)
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/edit.html.erb
<div class="row">
  <div class="col-md-4 col-lg-offset-4">
    <div class="panel panel-default set-panel">
      <div class="panel-body">
        <div class="page-header">
          <h3 class="title">Edit Category</h3>
        </div>
        <p class="about"> Guidelines for categories: </p>
        <ul class="list-style">
          <li>&raquo; Make sure the topic is appropriate.</li>
          <li>&raquo; Keep it simple.</li>
          <li>&raquo; Smile when you type.</li>
        </ul>
        <hr style="border-color: #eee;">
        <%= form_for @topic do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control', placeholder: "Enter category name" %>
          </div>

          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, rows: 6, class: 'form-control', placeholder: "Enter category description" %>
          </div>

          <div class="form-group">
            <%= f.label :public do %>
              <%= f.check_box :public %> Public category
            <% end %>
          </div>
          <%= f.submit "Save", class: 'btn btn-success' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/topics/index.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="page-header" style="margin-top: 25px;">
      <h3 class="title">Categories</h3>
    </div>
    <% if policy(Topic.new).create? %>
      <%= link_to new_topic_path, class: 'btn btn-success' do %>
        <span class="glyphicon glyphicon-plus"></span> New Topic
      <% end %>
    <% end %>
    <% @topics.each do |topic| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to topic.name, topic %>
          </h4>
          <small>
            <%= topic.description %>
          </small>
        </div>
      </div>
      <hr>
    <% end %>
    <%= will_paginate @index, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="row">
  <div class="col-md-4 col-lg-offset-4">
    <div class="panel panel-default set-panel">
      <div class="panel-body">
        <div class="page-header">
          <h3 class="title">New Category</h3>
        </div>
        <p class="about"> Guidelines for categories: </p>
        <ul class="list-style">
          <li>&raquo; Make sure the topic is appropriate.</li>
          <li>&raquo; Keep it simple.</li>
          <li>&raquo; Smile when you type.</li>
        </ul>
        <hr style="border-color: #eee;">
        <%= form_for @topic do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control', placeholder: "Enter category name" %>
          </div>

          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, rows: 6, class: 'form-control', placeholder: "Enter category description" %>
          </div>

          <div class="form-group">
            <%= f.label :public do %>
              <%= f.check_box :public %> Public category
            <% end %>
          </div>
          <%= f.submit "Save", class: 'btn btn-success' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/topics/show.html.erb
<!-- <h1><%#= @topic.name %></h1> -->


<div class="row">
  <div class="col-xs-12 col-md-4 pull-right" style="margin-bottom: 20px;">
    <% if policy(Post.new).create? %>
      <%= link_to new_topic_post_path(@topic), class: 'btn btn-success' do %>
        <span class="glyphicon glyphicon-plus"></span> New Place
      <% end %>
    <% end %>
    <% if policy(@topic).destroy? %>
      <%= link_to @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } do %> 
        <span class="glyphicon glyphicon-trash"></span> Delete Topic
      <% end %>
    <% end %>
  </div>
  <div class="col-md-8">
    <div class="page-header" style="margin-top: 25px;">
      <h3 class="title"><%= @topic.name %>
      <% if policy(@topic).update? %>
        <%= link_to edit_topic_path, class: 'btn btn-warning btn-xs' do %>
          <span class="glyphicon glyphicon-pencil"></span> Edit Topic
        <% end %>
      <% end %>
      </h3>
    </div>
    <p class="about"><%= @topic.description %></p>
    <br>
    <div class="row gap-style">
      <%= render @posts %>
    </div>
    <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
  </div> 

</div>