config/routes.rb
Bloccit::Application.routes.draw do

  get "posts/index"
  get 'tags/:tag', to: 'posts#index', as: :tag
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }


    resources :users, only: [:update, :show, :index]
    resources :posts, only: [:index]
    resources  :topics do
      resources :posts, except: [:index], controller: 'topics/posts' do
        resources :comments, only: [:create, :destroy]
        get '/up-vote' => 'votes#up_vote', as: :up_vote
        get '/down-vote' => 'votes#down_vote', as: :down_vote
        resources :favorites, only: [:create, :destroy]
      end
    end

  get 'autocomplete_location' => 'topics/posts#autocomplete_location'
  get 'about' => 'welcome#about'
  get 'index' => 'welcome#index'
  get 'privacypolicy' => 'welcome#privacypolicy'
  root to: 'welcome#index'
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessor :geolocation

  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  belongs_to :user
  belongs_to :topic
  belongs_to :location

  after_create :create_vote

  mount_uploader :image, ImageUploader
  acts_as_taggable

  default_scope { order('created_at DESC') }
  scope :visible_to, ->(user) {user ? all : joins(:topic).where('topics.public' => true)}

  validate :update_location
  
  validates :title, length: {minimum: 5}, presence: true
  validates :body, length: {minimum: 20}, presence: true
  validates :topic , presence: true
  validates :user, presence: true

  def up_votes
    self.votes.where(value: 1).count
  end

  def down_votes
    self.votes.where(value: -1).count
  end

  def points
    self.votes.sum(:value).to_i
  end

  def update_rank
    age = (self.created_at - Time.new(1970,1,1)) / 86400
    new_rank = points + age

    self.update_attribute(:rank, new_rank)
  end

  private

  def create_vote
    user.votes.create(value: 1, post: self)
  end

  def update_location
    loc = Geocoder.search(geolocation).first
    if loc.blank?
      errors.add(:location_id, "are not valid")
    else
      place = Location.find_or_create_place(loc.data["place_id"], loc)
      self.location_id = place.id
    end
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts, dependent: :destroy

  scope :public, -> { where(public: true) }
  scope :private, -> { where(public: false) }
  scope :visible_to, ->(user) {user ? all : where(public: true)}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
  	if params[:geolocation].blank?
  	  # if params[:tag]
     #    @posts = Post.tagged_with(params[:tag]).paginate(page: params[:page], per_page: 10)
     #  else
      @posts = Post.visible_to(current_user).where("posts.created_at > ?", 10.days.ago).paginate(page: params[:page], per_page: 10)
      # end
    else
      geo = Geocoder.search(params[:geolocation]).first
      @posts = if geo.blank?
        flash[:error] = "Location are not valid"
        []
      else
        loc = Location.where(place_id: geo.data["place_id"]).first
        @posts = loc.blank? ? [] : loc.posts.paginate(page: params[:page], per_page: 20)
      end
    end 
  end
end

app/controllers/topics/posts_controller.rb
class Topics::PostsController < ApplicationController
 
  def show
    @topic = Topic.find(params[:topic_id])
    authorize @topic
    @post = Post.find(params[:id])

    @comments = @post.comments
    @comment = Comment.new
  end


  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
    authorize @post
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = current_user.posts.build(post_params)
    @post.topic = @topic
    authorize @post

    if @post.save
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @post  = Post.find(params[:id])
    title = @post.title
    authorize @post

    if @post.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully."
      redirect_to @topic
    else
      flash[:error] = "There was an error deleting the post."
      redirect_to :show
    end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
    if @post.update_attributes(post_params)
      flash[:notice] = "Post was updated."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error updating the post. Please try again."
      render :edit
    end
  end

  def autocomplete_location
    location = Geocoder.search(params["term"])
    json = location.collect do |item| 
     { "id" => item.postal_code.to_s, 
       "label" => item.address, 
       "value" => item.address  
     }
   end
    render json: json
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image, :tag_list, :location_id, :geolocation)
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.visible_to(current_user).paginate(page: params[:page], per_page: 10)
    authorize @topics
  end

  def new
    @topic = Topic.new
    authorize @topic
  end

  def create
   @topic = Topic.new(topic_params)
    authorize @topic
    if @topic.save
      flash[:notice] = "Topic was saved."
      redirect_to @topic
    else
      flash[:error] = "There was an error saving your topic. Please try again."
      render :new
    end
  end

  def show
    @topic = Topic.find(params[:id]) 
    authorize @topic  
    @posts = @topic.posts.includes(:user).includes(:comments).paginate(page: params[:page], per_page: 10)
  end

  def edit
    @topic = Topic.find(params[:id])
    authorize @topic
  end

  def destroy
    @topic = Topic.find(params[:id])
    name = @topic.name
    
    authorize @topic

    if @topic.destroy
      flash[:notice] = "\"#{name}\" was deleted successfully."
      redirect_to topics_path
    else
      flash[:error] = "There was an erorr deleting the topic."
      render :show
    end

  end


  def update
    @topic = Topic.find(params[:id])
    authorize @topic
    if @topic.update_attributes(topic_params)
      redirect_to @topic
    else
      flash[:error] = "There was an error updating your topic. Please try again."
      render :edit
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:name,:description,:public)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/posts/_form.html.erb
<%= form_for [topic, post] do |f| %>
  <% if post.errors.any? %>
    <div class="alert alert-danger">
      <h4>There are <%= pluralize(post.errors.count, "error") %>.</h4>
      <ul>
        <% post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
  <%= form_group_tag(post.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
  <% end %>
  </div>
  <div class="form-group">
  <%= form_group_tag(post.errors[:body]) do %>
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
  <% end %>
  </div>
  <div class="form-group">
  <%= form_group_tag(post.errors[:tag_list]) do %>
    <%= f.label :tag_list %>
    <%= f.text_field :tag_list, class: 'form-control', placeholder: "Tags (seperated by commas)" %>
  <% end %>
  </div>

  <div class="form-group">
  <%= form_group_tag(post.errors[:location_id]) do %>
    <%= f.label :location_id %>
    <% location = post.new_record? ? "" : (post.location_id.to_i.eql?(0) ? "" : (post.location.address rescue "")) %>
    <%= autocomplete_field_tag "post[geolocation]", location, autocomplete_location_path, class: 'form-control', placeholder: "Enter post location"  %>
  <% end %>
  </div>

  <div class="form-group">
  <%= form_group_tag(post.errors[:image]) do %>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <% end %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/topics/posts/edit.html.erb
<div class="row">
  <div class="col-md-8 col-lg-offset-2">
    <div class="panel panel-default set-panel">
      <div class="panel-body">
        <div class="page-header">
          <h3 class="title">Edit Post</h3>
        </div>
        <p class="about"> Guidelines for categories: </p>
        <ul class="list-style">
          <li>&raquo; Make sure the topic is appropriate.</li>
          <li>&raquo; Keep it simple.</li>
          <li>&raquo; Smile when you type.</li>
        </ul>
        <hr style="border-color: #eee;">
        <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
      </div>
    </div>
  </div>
</div>

app/views/topics/posts/new.html.erb
<div class="row">
  <div class="col-md-8 col-lg-offset-2">
    <div class="panel panel-default set-panel">
      <div class="panel-body">
        <div class="page-header">
          <h3 class="title">New Post</h3>
        </div>
        <p class="about"> Guidelines for categories: </p>
        <ul class="list-style">
          <li>&raquo; Make sure the topic is appropriate.</li>
          <li>&raquo; Keep it simple.</li>
          <li>&raquo; Smile when you type.</li>
        </ul>
        <hr style="border-color: #eee;">
        <%= render partial: 'form', locals: {topic: @topic, post: @post } %>
      </div>
    </div>
  </div>
</div>

app/views/topics/posts/show.html.erb
<div class="row" style="margin-top: 20px;">
  <div class="col-xs-12 col-lg-4 pull-right" style="z-index: 1;margin-bottom: 10px;">
    <div class="panel panel-default">
      <div class="panel-body">
        <h3><%= pluralize(@post.points, 'point') %></h3>
        <small>
          <%= pluralize(@post.up_votes, 'up vote') %>,
          <%= pluralize(@post.down_votes, 'down vote') %>
        </small><br>
        <div style="margin-top:10px;">
          <% if policy(@post).edit? %>
            <%= link_to edit_topic_post_path(@topic,@post), class: 'btn btn-warning btn-sm' do %>
              <span class="glyphicon glyphicon-pencil"></span> Edit
            <% end %>
          <% end %>

          <% if policy(@post).destroy? %>
            <%= link_to [@topic, @post], method: :delete, class: 'btn btn-danger btn-sm', data: { confirm: 'Are you sure you want to delete this post?'} do %>
              <span class="glyphicon glyphicon-trash"></span> Delete Post
            <% end %>
          <% end %>
        </div>
        <%= render partial: 'favorites/favorite', locals: {topic: @topic, post: @post} %>
      </div>
    </div>
  </div>

  <div class="col-lg-8">
    <div>
      <%= render partial: 'votes/voter', locals: {topic: @topic, post: @post} %>
      <h1><%= markdown @post.title %> </h1>
      <small>
        <%= image_tag(@post.user.avatar.tiny.url) if @post.user.avatar? %>
        submitted <%= time_ago_in_words(@post.created_at) %> ago by
        <%= @post.user.name %>
      </small>
    </div>
    <p><%= markdown @post.body %></p>
    <p> Tags: <%= raw @post.tag_list.map {|t| link_to t, tag_path(t), class: "label label-orange" }.join(' ') %> </p>
    <p> Location: <%= @post.location.address rescue ""%>
    <hr/>
    <p><%= image_tag(@post.image_url) if @post.image? %></p>
    <h2 class='js-comments-count'><%= @comments.count %> Comments</h2>
    <div class='js-comments'>
      <%= render partial: 'comments/comment', collection: @comments, locals: {topic: @topic, post: @post} %>
    </div>
    <%if policy(@comment).create? %>
      <hr>
      <p><%= render partial: 'comments/form', locals: {topic: @topic, post: @post, comment: @comment}  %></p>
    <% end %>
  </div>
  
</div>