config/routes.rb
Bloccit::Application.routes.draw do

  get "posts/index"
  get 'tags/:tag', to: 'posts#index', as: :tag
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }


    resources :users, only: [:update, :show, :index]
    resources :posts, only: [:index]
    resources  :topics do
      resources :posts, except: [:index], controller: 'topics/posts' do
        resources :comments, only: [:create, :destroy]
        get '/up-vote' => 'votes#up_vote', as: :up_vote
        get '/down-vote' => 'votes#down_vote', as: :down_vote
        resources :favorites, only: [:create, :destroy]
      end
    end

  get 'autocomplete_location' => 'topics/posts#autocomplete_location'
  get 'about' => 'welcome#about'
  get 'index' => 'welcome#index'
  get 'privacypolicy' => 'welcome#privacypolicy'
  root to: 'welcome#index'
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery# with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end


  private

  def mobile_device?
    request.user_agent =~ /Mobile|webOS/
  end
  helper_method :mobile_device?

end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
    if errors.any?
      content_tag :div, capture(&block), class: 'form_group has-error'
    else
      content_tag :div, capture(&block), class: 'form_group'
    end
  end

  def markdown(text)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render text).html_safe
  end

  def comment_url_helper(comment)
    post = comment.post
    topic = post.topic
    [topic, post, comment]
  end

end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Sentro", index_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Categories", topics_path %></li>
        <li><%= link_to "Trending", posts_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Privacy", privacypolicy_path %></li>
      </ul>
      <p class="navbar-text navbar-right">
      <% if current_user  %>
      <%= image_tag(current_user.avatar.tiny.url) if current_user.avatar? %>
        Hello <%= link_to (current_user.name || current_user.email), current_user %>!

        <%= link_to edit_user_registration_path, class: 'btn btn-orange btn-sm' do %> 
        <span class="glyphicon glyphicon-user"></span>
        <% end %>
        
        <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-orange btn-sm' do %>
        <span class="glyphicon glyphicon-log-out"></span>
        <% end %>

      <% else  %>
        <%= link_to "Sign In", new_user_session_path  %> |
        Sign in with <%= link_to "Facebook", user_omniauth_authorize_path(:facebook) %> or
        <%= link_to "Sign Up", new_user_registration_path %>
      <% end %>
      </p>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>